Affymetrix GeneChip Experiment Information
Version	1

[Sample Info]
Chip Type	HG-U133_Plus_2
Chip Lot	
Operator	maduser
Sample Type	Human
Description	
Project	MAD1044-001
Comments	
Solution Type	
Solution Lot	

[Fluidics]
Protocol	
Station	
Module	
Hybridize Date	May 30 2006 03:52PM

[Scanner]
Pixel Size	1.56
Filter	570
Scan Temperature	
Scan Date	May 30 2006 04:04PM
Scanner ID	50101370
Number of Scans	1
Scanner Type	M10
