Affymetrix GeneChip Experiment Information
Version	1

[Sample Info]
Chip Type	Mapping50K_Hind240
Chip Lot	
Operator	gxing
Sample Type	Mapping
Description	
Project	CCNT_100k_PE_Hind
Comments	
Solution Type	
Solution Lot	

[Fluidics]
Protocol	
Completed
Station	
Module	
Hybridize Date	Sep 17 2004 12:29PM

[Scanner]
Pixel Size	
Filter	
Scan Temperature	
Scan Date	Sep 17 2004 12:29PM
Scanner ID	70101100
Number of Scans	1
Scanner Type	M10
