<?XML VERSION="1.0" ENCODING="UTF-8"?>

<CHANNEL HREF="http://www.iechannelguide.com/guide/pt/pt_br.asp">
<SELF HREF="http://www.iechannelguide.com/guide.cdf?loc=pt_br"/>
    <ABSTRACT>O Microsoft Channel Guide apresenta os principais parceiros de conteúdo do mercado e possibilita a pesquisa a canais do mundo todo. Use-o para descobrir conteúdos interessantes e adicioná-los a sua barra de canais.</ABSTRACT> 
</CHANNEL>
