<?XML VERSION="1.0" ENCODING="UTF-8"?>

<CHANNEL HREF="http://www.infordesporto.pt/inforcanal/">
    <ABSTRACT>Informação Desportiva diária sobre todas as modalidades. Resultados em tempo real, videos dos golos, fotos dos jogadores, estatística oficial, cartoons, agenda desportiva, espaço de dabates, acesso a base de dados com tudo sobre o Campeonato Navional de Futebol da 1ª Divisão e da Selecção Nacional e grande destaque para a Liga Profissional de Basquetebol, o Andebol, Ténis, Montanhismo e sempre mais.</ABSTRACT>
</CHANNEL>
