<?XML VERSION="1.0" ENCODING="UTF-8"?>

<CHANNEL HREF="http://www.iechannelguide.com/guide/ru/ru_ru.asp">
<SELF HREF="http://www.iechannelguide.com/guide.cdf?loc=ru_ru"/>
    <ABSTRACT>Путеводитель Microsoft по каналам вещания представляет ключевые источники информации в Интернете и позволяет производить поиск новых каналов во всем мире. С его помощью вы сможете найти и добавить к Вашей панели переключения каналов наиболее интересные информационные источники.</ABSTRACT> 
</CHANNEL>
