<?XML VERSION="1.0" ENCODING="UTF-8"?>

<CHANNEL HREF="http://www.cityline.ru/obs/">
    <ABSTRACT>"Moscow Observer" is the first Moscow`s web  site, dedicated to city`s cultural life and entertainment. Daily updated listings of all Moscow`s cultural and recreational events, huge amounts of cinema and music news, reviews on CD`s, videos and books, interviews, art projects, special pages. Dedicated to city`s most known artists and much more. "Moscow Observer", founded a half year ago, is already the most popular infotainment site for Moscow`s citizens.</ABSTRACT>
</CHANNEL>
