<?XML VERSION="1.0" ENCODING="windows-1250"?>

<CHANNEL HREF="http://www.iechannelguide.com/guide/sl/sl_si.asp">
<SELF HREF="http://www.iechannelguide.com/guide.cdf?loc=sl_si"/>
    <ABSTRACT>Microsoftov vodič po kanalih predstavlja partnerje, ki ponujajo najboljšo vsebino in omogoča iskanje kanalov po vsem svetu. Uporabite ga za iskanje in dodajanje zanimivih vsebin v vašo vrstico kanalov.</ABSTRACT> 
</CHANNEL>
