<?XML VERSION="1.0" ENCODING="windows-1252"?>

<CHANNEL HREF="http://www.iechannelguide.com/guide/sv/sv_se.asp">
<SELF HREF="http://www.iechannelguide.com/guide.cdf?loc=sv_se"/>
    <ABSTRACT>Microsoft Kanalguide visar branschens ledande informationsleverantörer och låter dig söka bland kanaler från hela världen. Använd den för att hitta och lägga till intressanta kanaler till Kanalfältet.</ABSTRACT> 
</CHANNEL>
