<?XML VERSION="1.0" ENCODING="windows-1252"?>

<CHANNEL HREF="http://www.iechannelguide.com/guide/zh/zh_sg.asp">
<SELF HREF="http://www.iechannelguide.com/guide.cdf?loc=zh_sg"/>
    <ABSTRACT>The Microsoft Channel Guide showcases the top content partners in the industry and lets you search for channels from around the world. Use it to find and add great content to your channel bar.</ABSTRACT> 
</CHANNEL>
