#!/usr/bin/env python3

import binascii
import functools
import re
import glob
import sys
import os
from itertools import islice
import fnmatch
import subprocess
import codecs
from os import listdir
from os.path import isfile, join


filepath = '../list7.txt'
mypath = "./"
with open(filepath) as fp:
   for cnt, line in enumerate(fp):
        line = line.replace('\n', '').replace('\r', '')
        i = [f for f in listdir(mypath) if isfile(join(mypath, f))]
       #glob_results = glob.glob('../*')
       #glob_results = sorted(glob_results)
       #for i in glob_results:
        #print (i)
        with open(i[0], "rb") as f:
        #print ("Searching " + i + " for " + line)
            text = str(f.read()) # This will return the contents of the file in string format
            #print (text)
            
            p = re.compile(re.escape(line))
            print ("Searching for " )
            print (p)
            print (" in " + i[0])
            try:
                location = re.search(p, text).group()
            except AttributeError:
                continue
            #location = re.search(line, text)
            #print (location)
            if location: 
                print ("Found " + location + " in file " + i[0])
            f.close()
            #print ("Found " + location + " in file " + i)
            #if re.search(r'line', fd):
                #print("found match on " + line)
